Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${self:service}-repo'
      Tags:
        - Key: 'adsk:moniker'
          Value: '${self:custom.config.moniker}'