Resources:
  FargateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${self:service}-ecs-sg"
      GroupDescription: Allow all outbound traffic, no inbound
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 8080
          CidrIp: 10.0.0.0/8
          Description: HTTP
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 8080
          CidrIp: 10.0.0.0/8
          Description: HTTPS
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
      VpcId: "${self:custom.config.vpcId}"